In [11]:
import numpy as np
import cv2

In [12]:
img = cv2.imread('original.jpeg')
# img = cv2.resize(img,(500,500))

In [13]:
height,width,pixels = img.shape
print("height ",height,"\nwidth",width)

height  1280 
width 960


In [14]:
# Decimal to Binary convertor
def dec2bin(dec):
    inverse = ''
    binary = ''
    while dec != 0:
        inverse = inverse + str( int(dec % 2) )
        dec = int(dec / 2)
    if len(inverse) <= 8:
        size = len(inverse)
        for i in range(8-size):
            inverse = inverse + '0'
    for i in range(len(inverse)-1,-1,-1):
        binary = binary + str(inverse[i])
    return binary

In [15]:
# Binary to Decimal convertor
def bin2dec(binar):
    binar = int(binar)
    dec = 0
    i = 0
    while binar > 0:
        dec = dec + (int(binar%10)*np.power(2,i))
        i = i+1
        binar = int(binar/10)
    return dec

In [16]:
# Secret Message into ASCII and ASCII into Binary format
file = open('input.txt','r')
secret_message = ''
for line in file.readlines():
    secret_message = secret_message + str(line)
    
binary = ''
for pos in range(len(secret_message)):
    if ord(secret_message[pos]) <= 255:
        binary = binary + str(dec2bin(ord(secret_message[pos]))) # coverting Secret code into ASCII and ASCII into Binary.
#print("Binary Code = ",binary)

TypeError: 'int' object is not callable

In [7]:
len_binary = len(binary)
print("text_length = ",len_binary)
k = 0
steagno_img = np.zeros((height,width,3),np.uint8) # Initializing the steagno image with original image.

for i in range(height):
    for j in range(width):
        if k < len_binary: 
            b,g,r = img[i,j] # blue, green , red values in a pixel.
            #print(np.dtype(b))
            #print(b,g,r)
            bin_b = int(dec2bin(b)) # binary form of blue pixel value.
            bin_g = int(dec2bin(g)) # binary form of green pixel value.
            bin_r = int(dec2bin(r)) # binary form of red pixel value.
            #print(bin_b,bin_g,bin_r)
            
            if k < len_binary:
                #print('bin_b ',bin_b)
                if int(bin_b % 10) == int(binary[k]):
                    k = k+1
                else:
                    if int(bin_b%10) == 0:
                        bin_b = (int(bin_b/10)*10) + 1
                    else:
                        bin_b = int(bin_b/10)*10
                    k = k+1
                #print('bin_b ',bin_b)
                    
            if k < len_binary:
                #print('bin_g ',bin_g)
                if int(bin_g % 10) == int(binary[k]):
                    k = k+1
                else:
                    if int(bin_g%10) == 0:
                        bin_g = (int(bin_g/10)*10) + 1
                    else:
                        bin_g = int(bin_g/10)*10
                    k = k+1
                #print('bin_g ',bin_g)
                
            if k < len_binary:
                #print('bin_r ',bin_r)
                if int(bin_r % 10) == int(binary[k]):
                    k = k+1
                else:
                    if int(bin_r%10) == 0:
                        bin_r = (int(bin_r/10)*10) + 1
                    else:
                        bin_r = int(bin_r/10)*10
                    k = k+1
                #print('bin_r ',bin_r)
            
            #print(bin_b,bin_g,bin_r)
            # Updating the original Pixel values. 
            b = np.uint8(bin2dec(bin_b))
            g = np.uint8(bin2dec(bin_g))
            r = np.uint8(bin2dec(bin_r))
            steagno_img[i,j] = [b,g,r]
            #print(img[i,j],steagno_img[i,j])
                
        else:
            break

text_length =  94960


In [8]:
cv2.imwrite('steagno_image.png',steagno_img)

True

In [9]:
steagno1_img = cv2.imread('steagno_image.png')
#print(steagno_img[0,0],img[0,0])

In [10]:
extracted_code = ''
for i in range(100):
    for j in range(960):
        b1,g1,r1 = steagno1_img[i,j] # blue, green , red values in a pixel.
        bin_b1 = int(dec2bin(b1)) # binary form of blue pixel value.
        bin_g1 = int(dec2bin(g1)) # binary form of green pixel value.
        bin_r1 = int(dec2bin(r1)) # binary form of red pixel value.
            
        extracted_code = extracted_code + str(int(bin_b1%10)) + str(int(bin_g1%10)) + str(int(bin_r1%10))
print("Code Extraction Completed.")
#for i in range(len(binary)):
#    print(extracted_code[i],' ',binary[i])
print("Now decoding the message.")
word = ''
for len in range(0,len(extracted_code),8):
    #print(extracted_code[len:(len+8)],'  ',chr(bin2dec(int(extracted_code[len:(len+8)]))))
    word =  word + str(chr(bin2dec(int(extracted_code[len:(len+8)]))))
print(word)

Code Extraction Completed.
Now decoding the message.
ÿÿÿÿÿÿÿÿøÿÿÿàøÿÿÿÿÿÀÿÿÿÿÿÿÿÿÿÿÿÿÿþm·$8’NürI¶Ûbœÿÿÿÿ~þÆän7$ý·#r6Ë|~à¶Ûm¶Ûm­¶í©+mV«mU[U­$­Äìqr7#rI$àw$n6Ûr7#nI4pâ7#ààpãó‰©X댓–`s¶n4’p•Kq°*©)&0ã±n¤Œµ$ª´í¶8âN9ÆãnM€ÄrRm¹mÆ܎8Îü4gG	9$­üøþ8Uµá;Ìf8jÏ1ZÛGàÀÛª:ԕؖÛ$”–I%j¶©$q¼á"I+·‹vµUN%$ª**¬¬²øâq:FÛÿÜnFç'd¸áɶª­J«UÇbvÙÈøećþ§#àÀþԒ$˜ãrÛSm¤¬é\mµT•JÚªµS¶n7$r8ã’8Ûn7#’7Ž7$r6ے:’Äìdÿÿÿÿÿÿüÿÿÿÿàøÿÿÿÿÿøÿÿÿÿÿÿÿÿÿÿÿÿÿÿm·$$’Nü|I¶ÛZœÿÿÿÿ~pâ9#r7$ý·#r6Ë`~à¶Ô­¶Ûm­¶íI[mª«mVÚª®¥mÄìNr7#rI$w$n7r7#m¶Ëpâ7$àà~ÿðàpŒNª©oc–œ}±mµmsj´â,¹œð4jªt©+RT¶Ä’NÙÇ-²8ÛümqÇ’I#n7¾àÞ71Å%UüpÿŽã‚j¾ÃR–uAº¥@üqøÛmÅ$•ÇiØëiJ¥UI'#Ž<@⭉â¥y«…VI$‰:Ú­ÉS¯]Ç䝎Æ7$ñÜq¹ ÛexpàI+RI%mÛm±&GyÄ¿×ÿñÇT­8ç#m$¬nT«é\mµ+RµZ•¶ÜNqÉm·mÇ#n7#’7$‘ÈÛr7#qº’ØìDÿÿÿÿÿÿ~?ÿÿÿüøÿÿÿÿÿøÿÿÿÿÿÿÿÿÿÿÿÿÿÿm·#ĝ¶ÿüI¶Úšÿÿÿÿÿ~üàvãr7$á¹#r6Ë`~à¶Ú•¶Ûm­¶Ò¶Ûm©[mVڕ®¥mÄã±r7#rI$7#r7#r7#’FÛpâ9$àà~ÿðàpÿ‚N¶¨ëp“–|IÙ·s‹ø «•VªN»Öڒà|Nþ¥jJÕlÄà&=’’Fã’HÜr6ÎãÀ"9	Ù*’ÇàÀ}ª>nìRèv¿YU@à

In [11]:
for i in range(10):
    for j in range(20):
        print(steagno1_img[i,j],img[i,j])

[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [224 236 242]
[225 237 243] [225 237 243]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[223 235 241] [223 235 241]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 237 243]
[225 237 243] [225 2

In [12]:
print(chr(61656))


